apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-delete-task-api-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: delete-tasks-api.applicationtesting.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-delete-tasks-api-service
                port:
                  number: 80
